############################################################################
# Contest 2026 team 435 (UdifyFun) apollia_hub - Makefile
############################################################################

include $(APPDIR)/Make.defs

PROGNAME  = apollia_hub
PRIORITY  = SCHED_PRIORITY_DEFAULT
STACKSIZE = 8192
MODULE    = $(CONFIG_LVX_USE_DEMO_CONTEST2026_435_APOLLIA_HUB)

MAINSRC = apollia_hub_main.c

include $(APPDIR)/Application.mk
